### ISSUE TITLE
Fork synchronization 

### ISSUE THREAD

**Issue by skodapetr** [id-sk/id-sk-frontend#400]
Following my comment at #384 it would be nice to clarify what is the selected way of synchronization with the https://github.com/alphagov/govuk-frontend repository. This should be either in the readme file or the contribution guide. For example can issues in the ```src/govuk``` directory be fixed here?

**Comment by robertsopko** [comment]
Hello, we are syncing with the govuk-frontend repository within every major release of id-sk-frontend, the next major release should be later this year. There is a branch called govuk-4.6-rebase where we keep the sync with the latest govuk-frontend (https://github.com/id-sk/id-sk-frontend/tree/feature/govuk-4.6-rebase). The issues you mentioned should be fixed in that branch.
